# Generated by Django 3.0.8 on 2020-08-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200831_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profileimg',
            field=models.ImageField(default='img.jpg', upload_to='media'),
        ),
    ]
