# Generated by Django 3.0.8 on 2020-09-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profileimg',
        ),
    ]
