# Generated by Django 3.0.8 on 2020-08-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
