# Generated by Django 3.0.8 on 2020-08-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200822_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CP', 'Cupcakes'), ('CK', 'Cake'), ('FD', 'Fondant'), ('BC', 'Buttercream'), ('PS', 'Pastry'), (None, '')], default=None, max_length=100)),
            ],
        ),
    ]
