# Generated by Django 3.0.8 on 2020-08-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('CP', 'Cupcakes'), ('CK', 'Cake'), ('FD', 'Fondant'), ('BC', 'Buttercream'), ('PS', 'Pastry'), (None, '')], default=None, max_length=20, null=True),
        ),
    ]
