# Generated by Django 3.0.8 on 2020-10-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200901_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Cupcakes', 'Cupcakes'), ('Cake', 'Cake'), ('Fondant', 'Fondant'), ('Buttercream', 'Buttercream'), ('Pastry', 'Pastry'), (None, '')], default=None, max_length=20, null=True),
        ),
    ]
